### ISSUE TITLE
使用sqlite替代redis

### ISSUE THREAD

**Issue by zhu327** [RanKKI/BangumiBot#20]
减少部署依赖, 挂载目录方便操作

**Comment by RanKKI** [comment]
确实， redis 在这里其实没啥意义，完全可以被替代， 我想下怎么改下载队列。

**Comment by albicoccca** [comment]
> 确实， redis 在这里其实没啥意义，完全可以被替代， 我想下怎么改下载队列。

真的要这么改了吗，那我新nas准备观望一下了，现在太懒想一次搞好躺平...

**Comment by RanKKI** [comment]
> > 确实， redis 在这里其实没啥意义，完全可以被替代， 我想下怎么改下载队列。
> 
> 真的要这么改了吗，那我新nas准备观望一下了，现在太懒想一次搞好躺平...

想了一下，想加个功能， 还是保留 redis 吧。

**Comment by albicoccca** [comment]
> > > 确实， redis 在这里其实没啥意义，完全可以被替代， 我想下怎么改下载队列。
> > 
> > 
> > 真的要这么改了吗，那我新nas准备观望一下了，现在太懒想一次搞好躺平...
> 
> 想了一下，想加个功能， 还是保留 redis 吧。

好的，那我上手了试错了，水平太差 T T

**Comment by albicoccca** [comment]
> > > 确实， redis 在这里其实没啥意义，完全可以被替代， 我想下怎么改下载队列。
> > 
> > 
> > 真的要这么改了吗，那我新nas准备观望一下了，现在太懒想一次搞好躺平...
> 
> 想了一下，想加个功能， 还是保留 redis 吧。

好的，那我上手了试错了，水平太差 T T
