### ISSUE TITLE
你好，我群晖docker启动保错了，请问是怎么回事哟

### ISSUE THREAD

**Issue by y1834257499** [RanKKI/BangumiBot#24]
![image](https://github.com/RanKKI/BangumiBot/assets/47782692/e980121f-d5ec-46a3-bf64-acdf60582258)
![image](https://github.com/RanKKI/BangumiBot/assets/47782692/cec6c18d-7ded-4fec-a146-715b3c5d143c)

**Comment by RanKKI** [comment]
能看一下你的配置文件么？

**Comment by y1834257499** [comment]
{
   "CapAdd" : null,
   "CapDrop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enable_service_portal" : null,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "C.UTF-8"
      },
      {
         "key" : "GPG_KEY",
         "value" : "A035C8C19219BA821ECEA86B64E628F8D684696D"
      },
      {
         "key" : "PYTHON_VERSION",
         "value" : "3.11.3"
      },
      {
         "key" : "PYTHON_PIP_VERSION",
         "value" : "22.3.1"
      },
      {
         "key" : "PYTHON_SETUPTOOLS_VERSION",
         "value" : "65.5.1"
      },
      {
         "key" : "PYTHON_GET_PIP_URL",
         "value" : "https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py"
      },
      {
         "key" : "PYTHON_GET_PIP_SHA256",
         "value" : "96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207"
      },
      {
         "key" : "S6_SERVICES_GRACETIME",
         "value" : "30000"
      },
      {
         "key" : "S6_KILL_GRACETIME",
         "value" : "60000"
      },
      {
         "key" : "S6_CMD_WAIT_FOR_SERVICES_MAXTIME",
         "value" : "0"
      },
      {
         "key" : "S6_SYNC_DISKS",
         "value" : "1"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "HOME",
         "value" : "/volume2/video/视频/电视"
      },
      {
         "key" : "TZ",
         "value" : "Asia/Shanghai"
      },
      {
         "key" : "PUID",
         "value" : "1000"
      },
      {
         "key" : "PGID",
         "value" : "1000"
      },
      {
         "key" : "UMASK",
         "value" : "022"
      }
   ],
   "exporting" : false,
   "id" : "93642a6123cb0cbdb72c56d4597d669c9b68faf3ab2469849939b1dcdee2a8fc",
   "image" : "estrellaxd/auto_bangumi:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "estrellaxd-auto_bangumi",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 7892,
         "host_port" : 7892,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/AutoBangumi/config",
         "mount_point" : "/app/config",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/AutoBangumi/data",
         "mount_point" : "/app/data",
         "type" : "rw"
      }
   ]
}

**Comment by y1834257499** [comment]
![image](https://github.com/RanKKI/BangumiBot/assets/47782692/548463c5-2ce0-4c16-a1c2-128b487fc5ef)

**Comment by RanKKI** [comment]
是个bug, 
简单的修复方法是设置 `BANGUMI_SEEDING` 到 `no`

我会修一下， 保证在没定义的时候 也不会报错
